### ISSUE TITLE
Create a Function to constantly update the screen and elements positions

### ISSUE THREAD

**Issue by VRamazing** [StevenCopeland/SpaceInvaders#4]
Please look over the code of conduct before creating an issue.

Make sure that your issue is in accordance wit the following rules. Put in X between the ones that our.

- [X] I have looked over the code of conduct, and the content of the issue is inline with it.
- [X] I have checked if this bug and/or feature has been already created an issue of.

**Comment by StevenCopeland** [comment]
Could you add explain your issue in a little bit more detail?

**Comment by VRamazing** [comment]
The code is too fragmented.Whenever you shoot you are using an interval to updating function.Which is a good way.I am saying we should use that interval and make it a global function and use it to update all the position of all elements. If you want to see an example refer to this code.  https://codepen.io/vramazing/pen/mBmaJm or Fork at https://github.com/igameproject/Breakout

**Comment by StevenCopeland** [comment]
@VRamazing How is it looking now?

**Comment by VRamazing** [comment]
The code still seems fragmented.I am thinking about writing my own space invaders from scratch.Maybe you could benefit from it.If you want me to extend current code I can do that as well.

**Comment by StevenCopeland** [comment]
@VRamazing If you want to you can!
