### ISSUE TITLE
Reorganize code to increase readability and Understandability.Add comments.

### ISSUE THREAD

**Issue by VRamazing** [StevenCopeland/SpaceInvaders#5]
Please look over the code of conduct before creating an issue.

Make sure that your issue is in accordance wit the following rules. Put in X between the ones that our.

- [X] I have looked over the code of conduct, and the content of the issue is inline with it.
- [X] I have checked if this bug and/or feature has been already created an issue of.

Its really difficult to understand what the code does for newbie.Plus the statement ctx.fillRect(mx, my, 30, 30); is used multiple time which is not a good coding convention.It can easily be converted into a loop.
The variable names must be changed to something more readable and intuitive.
Comments should follow for blocks of code if necessary

**Comment by StevenCopeland** [comment]
I'll see if I can do something about that.

**Comment by StevenCopeland** [comment]
Look at the latest commit.

**Comment by VRamazing** [comment]
Yes it is better.Check the merge request I have done my part.

**Comment by StevenCopeland** [comment]
Merged your PR. Closing this issue....
