### ISSUE TITLE
Problems with firing bullet

### ISSUE THREAD

**Issue by StevenCopeland** [StevenCopeland/SpaceInvaders#8]
If you move a little bit over and then you fire a bullet(the first time) the bullet will fire from the original spot. 

Here is a picture:

![image](https://user-images.githubusercontent.com/26176516/31047661-a2089892-a5dc-11e7-8d7f-4af52bb9abb5.png)

**Comment by pradeephbac** [comment]
Hi , could I contribute to resolve this issue ?

**Comment by devinchen** [comment]
Try this

```
//Bullet Position
var sx, sy;

var shoot = function() {
	if (!sx || !sy) {
		sx = x + 10;
		sy = y - PLAYER_HEIGHT/2;
	}
	...rest of the code
}
```

**Comment by StevenCopeland** [comment]
@pradeephbac You can contribute if you want to. @devinchen I'll try that.

**Comment by StevenCopeland** [comment]
@devinchen That didn't work. At least I think not. Try forking the repo and creating a PR. Then you can test your code and see if it works.

**Comment by pradeephbac** [comment]
I created PR and resolved the error.
Edited Shoot function

// Shooting function for the player
```
var shoot = function() { 
	if (sx != x || sy != y) {
		sx=x;
		sy=y;
		if (sy >= 0) { // Checks if the bullet is passed the end of the screen.
			if (bulletMovement) return;
			bulletMovement = setInterval(function() {
				ctx.clearRect(sx, sy, BULLET_SIZE, BULLET_SIZE);
				sy -= BULLET_SIZE;
				ctx.fillStyle = "yellow";
				ctx.fillRect(sx , sy, BULLET_SIZE, BULLET_SIZE);
			}, 10)
		} else { // if the bullets are passed the end of the screen, set the position to normal and erase the square.
			ctx.clearRect(sx, sy, BULLET_SIZE, BULLET_SIZE)
			sx = x  ; //XPoition of user bullet origin
			sy = y - PLAYER_HEIGHT/2 ;//YPosition of user bullet origin.
		}
	}else{
		if (sy >= 0) { // Checks if the bullet is passed the end of the screen.
			if (bulletMovement) return;
	
			bulletMovement = setInterval(function() {
				ctx.clearRect(sx, sy, BULLET_SIZE, BULLET_SIZE);
				sy -= BULLET_SIZE;
				ctx.fillStyle = "yellow";
				ctx.fillRect(sx , sy, BULLET_SIZE, BULLET_SIZE);
			}, 10)
		} else { // if the bullets are passed the end of the screen, set the position to normal and erase the square.
			ctx.clearRect(sx, sy, BULLET_SIZE, BULLET_SIZE)
			sx = x  ; //XPoition of user bullet origin
			sy = y - PLAYER_HEIGHT/2 ;//YPosition of user bullet origin.
		}

	}
	
}
```

**Comment by StevenCopeland** [comment]
Do you mind resolving the conflicts?

**Comment by pradeephbac** [comment]
As I see , Only those with write access to this repository can merge pull requests and resolve conflict

**Comment by StevenCopeland** [comment]
@pradeephbac You are correct. But, if you merge the latest commits from my branch to yours, it would resolve the conflicts(If you are not careful though, it will overwrite your existing code). But don't worry about any more. Everything has been fixed(see #9 ).

**Comment by StevenCopeland** [comment]
This issue/feature has been resolved. :heavy_check_mark:

**Comment by pradeephbac** [comment]
@StevenCopeland Thanks for nice response to a contributor by another. Its nice to see how that issue was resolved here. Cheers.
